set-option -g prefix C-x
set-option -g base-index 1
set-option -g mode-keys vi
set-option -g status-keys emacs

set-option -g status-style 'bg=#181818,fg=#a0a0a0'
set-option -g status-right '#{pane_title} %H:%M'
set-option -g status-right-length 80

bind C-x send-prefix
bind h select-pane -t '{left-of}'
bind l select-pane -t '{right-of}'
bind k select-pane -t '{up-of}'
bind j select-pane -t '{down-of}'
