font_size 13
font_family menlo
cursor #d0d0d0
cursor_shape block
cursor_text_color #1f2329
foreground #d0d0d0
background #1f2329
background_opacity 1.0

#Scrolling
scrollback_lines 1000
scrollback_pager vim -c 'silent write! /tmp/kitty_scrollback_buffer | terminal cat /tmp/kitty_scrollback_buffer' -c 'only' -
map ctrl+shift+p launch --stdin-source=@screen_scrollback --type=overlay vim -c 'silent write! /tmp/kitty_scrollback_buffer | terminal cat /tmp/kitty_scrollback_buffer' -c 'only' -
map ctrl+shift+y show_scrollback
map ctrl+shift+g show_last_command_output
map ctrl+shift+j scroll_line_down
map ctrl+shift+k scroll_line_up
map ctrl+shift+d scroll_page_down
map ctrl+shift+u scroll_page_up

# Window layout
enabled_layouts splits:split_axis=horizontal
map ctrl+\ launch --location=vsplit
map ctrl+shift+\ launch --location=hsplit
map alt+h resize_window narrower 10
map alt+l resize_window wider 10
map alt+j resize_window shorter 5 
map alt+k resize_window taller 5
