font_size              25
font_family            family='Iosevka' style='extralight' features='-calt'
italic_font            family='Iosevka' style='extralight italic' features='-calt'
bold_font              family='Iosevka' style='regular' features='-calt'
bold_italic_font       family='Iosevka' style='regular italic' features='-calt'

background             #181818
foreground             #efefef
background_opacity     1

cursor_shape           block
cursor                 #efefef
cursor_text_color      #181818
cursor_blink_interval  0

remember_window_size   no
shell_integration      no-cursor
scrollback_lines       1000
scrollback_pager       vim -c 'silent write! /tmp/kitty_scrollback_buffer | terminal cat /tmp/kitty_scrollback_buffer' -c 'only' -

map ctrl+shift+p       launch --stdin-source=@screen_scrollback --type=overlay vim -c 'silent write! /tmp/kitty_scrollback_buffer | terminal cat /tmp/kitty_scrollback_buffer' -c 'only' -
map ctrl+shift+y       show_scrollback
map ctrl+shift+g       show_last_command_output
map ctrl+shift+j       scroll_line_down
map ctrl+shift+k       scroll_line_up
map ctrl+alt+j       scroll_page_down
map ctrl+alt+k       scroll_page_up
