let &t_SR = "\e[4 q" "StartReplace Mode : Underline
let &t_EI = "\e[2 q" "EndInsert Mode    : Block
set encoding=utf-8
set nocompatible
set relativenumber
set number
set signcolumn=no
set laststatus=2
set title
set titlestring=%f\ -\ Vim
set hidden
set cursorline

set tabstop=4
set softtabstop=4
set shiftwidth=4
set lcs=tab:»\ 
set list

set foldenable
set foldmethod=indent
set foldlevel=100

set colorcolumn=80
set nowrap
set textwidth=80
set smartindent
set autoindent
set scrolloff=8
set ttimeoutlen=50
set splitbelow
set splitright

set nohls
set incsearch
set ignorecase
set smartcase
set updatetime=10
set noswapfile
set undofile
set undodir=~/.local/state/vim/undo

let g:netrw_banner=0
let g:netrw_menu=0
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'
"let g:lsp_log_verbose=1
"let g:lsp_log_file=expand('~/vim-lsp.log')

syntax enable
filetype plugin indent on

set path+=**
set wildmenu
set wildoptions=pum,fuzzy
set pumheight=30
set wildignore+=node_modules/*,tags
set completeopt=menu,menuone,noselect,noinsert,popup

runtime ftplugin/man.vim
let g:ft_man_open_mode = 'vert'

set guioptions=aegit
set guifont=NotoSansM\ Nerd\ Font\ Mono\ ExtraCondensed\ ExtraLight\ 20
