set runtimepath+=~/.config/vim/

set encoding=utf-8
set nocompatible
set relativenumber
set number
set signcolumn=no

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set foldenable
set foldmethod=indent
set foldlevel=100

set colorcolumn=80
set nowrap
set textwidth=80
set smartindent
set autoindent

set nohls
set incsearch
set updatetime=50
set undofile
set undodir=~/.local/state/vim/undo

syntax enable
filetype plugin indent on

set path+=src/**,app/**
set wildmenu
set wildoptions=pum,fuzzy
set pumheight=30
set wildignore+=node_modules/*,tags
set completeopt=menu,menuone,noselect,noinsert,popup

call plug#begin()
  Plug 'prabirshrestha/vim-lsp'
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

runtime lsp-config.vim
runtime keymaps.vim
runtime color.vim

au Filetype json {
  set formatexpr=
  set formatoptions=
  set formatprg=json_pp
}

function! PrettierFormat(type)
  exec "'[,']!prettier --parser=typescript"
endfunction

function! ClangFormat(type)
  exec "'[,']!clang-format"
endfunction

au Filetype javascript,typescript {
  set tabstop=2
  set softtabstop=2
  set shiftwidth=2

  nmap <silent> gq :set opfunc=PrettierFormat<cr>g@
  vmap <leader>gp :!prettier --parser=typescript<cr>
}

au Filetype c,cpp {
  nmap <silent> gq :set opfunc=ClangFormat<cr>g@
}

au Filetype markdown {
  set formatexpr=
  set formatoptions=
  set formatprg=pandoc\ --to=gfm
}
