set runtimepath+=~/.config/vim/

set nocompatible
set relativenumber
set number
set signcolumn=no

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set foldenable
set foldmethod=indent
set foldlevel=100

set colorcolumn=80
set nowrap
set smartindent
set autoindent

set nohls
set incsearch
set updatetime=50
set undofile

syntax enable
filetype plugin indent on

set path+=src/**,app/**
set wildmenu
set wildoptions=pum,fuzzy
set pumheight=30
set wildignore+=node_modules/*,tags
set completeopt=menu,menuone,noselect,noinsert,popup

call plug#begin()
  Plug 'prabirshrestha/vim-lsp'
  Plug 'prabirshrestha/asyncomplete.vim'
  Plug 'prabirshrestha/asyncomplete-lsp.vim'
  " Plug 'girishji/scope.vim'
call plug#end()

runtime lsp-config.vim
runtime keymaps.vim
runtime color.vim

au Filetype json {
  set formatexpr=
  set formatoptions=
  set formatprg=json_pp
}

function! PrettierFormat(type)
  exec "'[,']!prettier --parser=typescript"
endfunction

au Filetype javascript,typescript {
  nmap <silent> gq :set opfunc=PrettierFormat<cr>g@
  vmap <leader>gp :!prettier --parser=typescript<cr>
}

au Filetype markdown {
  set formatexpr=
  set formatoptions=
  set formatprg=pandoc\ --to=gfm
}
